Repository qlicker/qlicker, pull requests merged in 2019-03, with the labels that each got.

#567 Add participation and averages to Session List card
  imports/api/grades.js
  imports/ui/SessionListItem.jsx
  imports/ui/pages/professor/manage_course.jsx
Labels: Medium priority, UI/UX, feature

#566 UI for grades dashboard. View grades by student, session, view all se…
  client/css/components/results.scss
  imports/ui/pages/course_grades.jsx
Labels: Changes Requested, Do Not Merge

#569 Implement grade table for students
  imports/startup/client/routes.jsx
  imports/ui/GradeTable.jsx
  imports/ui/StudentGradeTable.jsx
  imports/ui/pages/course_grades.jsx
  imports/ui/pages/grades_display_container.jsx
  imports/ui/pages/page_container.jsx
Labels: High priority, feature

#570 Implement grade table for session
  imports/startup/client/routes.jsx
  imports/ui/SessionGradeTable.jsx
  imports/ui/StudentGradeTable.jsx
  imports/ui/pages/course_grades.jsx
  imports/ui/pages/grades_display_container.jsx
  imports/ui/pages/page_container.jsx
Labels: High priority, UI/UX, feature

#572 Implement function to return random subset of questions filtered by tags and of a specified length
  imports/api/questions.js
  imports/ui/modals/CreatePracticeQuizModal.jsx
  imports/ui/pages/student/course.jsx
Labels: High priority, feature

#575 Issue/555 update grades dashboard
  .gitignore
  client/css/components/results.scss
  docs/Development-Data.md
  imports/api/grades.js
  imports/api/users.js
  imports/startup/client/routes.jsx
  imports/ui/GradeTable.jsx
  imports/ui/OverallGradeTable.jsx
  imports/ui/SessionGradeTable.jsx
  imports/ui/SessionListItem.jsx
  imports/ui/SessionResultsTable.jsx
  imports/ui/StudentGradeTable.jsx
  imports/ui/pages/course_grades.jsx
  imports/ui/pages/grades_display_container.jsx
  imports/ui/pages/page_container.jsx
  imports/ui/pages/professor/manage_course.jsx
  imports/ui/pages/professor/manage_courses.jsx
  imports/ui/pages/results_overview.jsx
  imports/ui/pages/student/course.jsx
Labels: High priority, feature
